---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: "{{values.name}}-on-pull-request"
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "2"
    pipelinesascode.tekton.dev/pipeline: "https://raw.githubusercontent.com/Jdubrick/rhdh-pipelines/yaml-lint/pac/pipelines/docker-build-ai-rhdh.yaml"
    pipelinesascode.tekton.dev/task-0: "https://raw.githubusercontent.com/Jdubrick/rhdh-pipelines/yaml-lint/pac/tasks/init.yaml"
    pipelinesascode.tekton.dev/task-1: "https://raw.githubusercontent.com/Jdubrick/rhdh-pipelines/yaml-lint/pac/tasks/git-clone.yaml"
    pipelinesascode.tekton.dev/task-2: "https://raw.githubusercontent.com/Jdubrick/rhdh-pipelines/yaml-lint/pac/tasks/buildah-ai-rhdh.yaml"
    pipelinesascode.tekton.dev/task-3: "https://raw.githubusercontent.com/Jdubrick/rhdh-pipelines/yaml-lint/pac/tasks/update-deployment.yaml"
    pipelinesascode.tekton.dev/task-4: "https://raw.githubusercontent.com/Jdubrick/rhdh-pipelines/yaml-lint/pac/tasks/show-sbom-rhdh.yaml"
    pipelinesascode.tekton.dev/task-5: "https://raw.githubusercontent.com/Jdubrick/rhdh-pipelines/yaml-lint/pac/tasks/summary.yaml"
  labels:
    argocd/app-name: test-linter-oct28
    janus-idp.io/tekton: test-linter-oct28
    backstage.io/kubernetes-id: test-linter-oct28
    backstage.io/kubernetes-namespace: rhdh-app
    app.kubernetes.io/part-of: test-linter-oct28
spec:
  params:
    - name: dockerfile
      value: {? {values.dockerfile: ''} : ''}
    - name: git-url
      value: '{{repo_url}}'
    - name: image-expires-after
      value: 5d
    - name: output-image
      value: "{{values.image}}:on-pr-{{revision}}"
    - name: path-context
      value: {? {values.buildContext: ''} : ''}
    - name: revision
      value: '{{revision}}'
    - name: event-type
      value: '{{event_type}}'
    - name: gitops-auth-secret-name
      value: {? {values.gitopsSecretName: ''} : ''}
  pipelineRef:
    name: docker-build-ai-rhdh
  workspaces:
    - name: git-auth
      secret:
        secretName: "{{git_auth_secret}}"
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
